## Numerical Computing with NumPy

Although the Python interpreter itself already brings a rich variety of data structures with it, NumPy and other libraries add to these in a valuable fashion. 

We will focuses on NumPy, which provides a multidimensional array object to store homogeneous or heterogeneous data arrays and supports vectorization of code.

We will cover the following data structures


*   ndarray (regular) - n-dimensional array object - Used for large arrays of numerical data
* ndarray (record) - 2-dimensional array object - Used for tabular data organized in columns




### Arrays with Python Lists
A simple list can already be considered a one-dimensional array:


In [1]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]

Since list objects can contain arbitrary other objects, they can also contain other list objects. In that way, two- and higher-dimensional arrays are easily constructed by nested list objects:

In [2]:
m = [v, v, v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

One can also easily select rows via simple indexing or single elements via double indexing (whole columns, however, are not so easy to select)

In [3]:
m[1]

[0.5, 0.75, 1.0, 1.5, 2.0]

In [4]:
m[1][0]

0.5

### The Python array Class
According to the python documentation: This module defines an object type which can compactly represent an array of basic
values: characters, integers, floating point numbers. Arrays are sequence types and
behave very much like lists, except that the type of objects stored in them is con‐
strained. The type is specified at object creation time by using a type code, which is a
single character.

In [5]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]

In [6]:
import array

a = array.array('f', v)
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0])

In [8]:
a.append(0.5)
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 0.5])

In [9]:
a.extend([5.0, 6.75])
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 0.5, 5.0, 6.75])

In [10]:
2 * a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 0.5, 5.0, 6.75, 0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 0.5, 5.0, 6.75])

Trying to append an object of a different data type than the one specified raises a
TypeError:

In [11]:
a.append('string')

TypeError: ignored

However, the array object can easily be converted back to a list object if such flexibility is required.

### Regular NumPy Arrays

Composing array structures with list objects works, somewhat. But it is not really
convenient, and the list class has not been built with this specific goal in mind. It
has rather a much broader and more general scope. The array class is a bit more spe‐
cialized, providing some useful features for working with arrays of data. However, a
truly specialized class could be really beneficial to handle array-type structures.

#### The Basics
numpy.ndarray is just such a class, built with the specific goal of handling ndimensional arrays both conveniently and efficiently—i.e., in a highly performant manner. The basic handling of instances of this class is again best illustrated by
examples:

In [12]:
import numpy as np

In [13]:
a = np.array([0, 0.5, 1.0, 1.5, 2.0])
a

array([0. , 0.5, 1. , 1.5, 2. ])

In [14]:
type(a)

numpy.ndarray

In [15]:
a = np.array(['a', 'b', 'c']) # Creates an ndarray object out of a list object with strs.
a

array(['a', 'b', 'c'], dtype='<U1')

In [17]:
a = np.arange(2, 20, 2) # np.arange() works similar to range()
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
a[5:] # With one-dimensional ndarray objects, indexing works as usual.

array([12, 14, 16, 18])

In [21]:
a[:2]

array([2, 4])

In [22]:
# A major feature of the ndarray class is the multitude of built-in methods. For instance:
a.sum()

90

In [23]:
a.std() # The standard deviation of the elements

5.163977794943222

In [24]:
a.cumsum() # The cumulative sum of all elements (starting at index position 0).

array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])

Another major feature is the (vectorized) mathematical operations defined on ndarray objects:

In [25]:
l = [0., 0.5, 1.5, 3., 5.] # Scalar multiplication with list objects leads to a repetition of elements
2 * l

[0.0, 0.5, 1.5, 3.0, 5.0, 0.0, 0.5, 1.5, 3.0, 5.0]

In [26]:
a # By contrast, working with ndarray objects implements a proper scalar multiplication

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
2 * a 

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36])

In [28]:
a ** 2 # This calculates element-wise the square values.

array([  4,  16,  36,  64, 100, 144, 196, 256, 324])

Universal functions are another important feature of the NumPy package. They are “universal” in the sense that they in general operate on ndarray objects as well as on basic Python data types. However, when applying universal functions to, say, a Python float object, you need to be aware of the reduced performance compared to the same functionality found in the math module

In [29]:
np.exp(a) # Calculates the exponential values element-wise

array([7.38905610e+00, 5.45981500e+01, 4.03428793e+02, 2.98095799e+03,
       2.20264658e+04, 1.62754791e+05, 1.20260428e+06, 8.88611052e+06,
       6.56599691e+07])

In [30]:
np.sqrt(a) # Calculates the square root for every element

array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766,
       3.46410162, 3.74165739, 4.        , 4.24264069])

In [31]:
np.sqrt(2.5) # Calculates the square root for a Python float object

1.5811388300841898

In [32]:
import math
math.sqrt(2.5) # The same calculation, this time with the math module

1.5811388300841898

In [33]:
math.sqrt(a) # The math lib cannot be applied to the ndarray object directly

TypeError: ignored

In [34]:
%timeit np.sqrt(2.5) # Applying the universal function np.sqrt() to a Python float object is much slower
                     # than the same operation with math.sqrt()

The slowest run took 42.63 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 835 ns per loop


In [35]:
%timeit math.sqrt(2.5)

The slowest run took 31.18 times longer than the fastest. This could mean that an intermediate result is being cached.
10000000 loops, best of 5: 108 ns per loop


### Multiple Dimensions

The transition to more than one dimension is seamless, and all features presented so far carry over to the more general cases. In particular, the indexing system is made consistent across all dimensions:


In [38]:
b = np.array([a, a * 2]) # Constructs a two dimensional ndarray object out of the one-dimensional one
b

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36]])

In [39]:
b[0] # Selects the first row

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [40]:
b[0, 2] # Selects the third element in the first row; indices are separated, within the brackets by a comma

6

In [41]:
b[:, 1] # Selects the second column

array([4, 8])

In [42]:
b.sum() # Calculates the sum of all values

270

In [43]:
b.sum(axis=0) # Calculates the sum alone the first axis (column wise)

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [44]:
b.sum(axis=1) # Calculates the sum along the second axis (row wise)

array([ 90, 180])

There are a number of ways to initialize (instantiate) ndarray objects. One is as presented before, via np.array. 

However, this assumes that all elements of the array are already available. In contrast, one might like to have the ndarray objects instantiated first to populate them later with results generated during the execution of code. To this end, one can use the following functions:

In [45]:
c = np.zeros((2, 3), dtype='i', order='C') # Creates an ndarray object prepopulated with zeros
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [48]:
c = np.ones((2, 3, 4), dtype='i', order='C') # Creates an ndarray object prepopulated with ones
c

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [49]:
d = np.zeros_like(c, dtype='f16', order='C') # The same, but takes another ndarray object to infer the shape
d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float128)

In [50]:
e = np.empty((2, 3, 2)) # Creates an ndarray object not prepoulated with anything (Numbers are bits present in memory)
e

array([[[4.68534485e-310, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [6.91643308e-310, 1.58817677e-052]],

       [[7.73422389e-091, 5.49167910e+174],
        [9.99506045e-048, 3.85340822e-057],
        [3.99910963e+252, 6.91662203e-310]]])